## config for prepping samples and hyperparamter tuning of VAE

cohort: PDAC

cofactor: 1.0

samples_tsv: ../analysis/pdac_analysis/PDAC_samples_paths.tsv #../../hmivae_runs/melanoma_imc_samples_paths.tsv #../../tidy_data/basel_samples.tsv #../../tidy_data/METABRIC_samples_paths.tsv 

tidy_output_dir:  ../analysis/pdac_analysis/vae_prep

hyperparams_tuning_dir: ../analysis/pdac_analysis/hyperparams_tuning

feature_data: ../../data/IMC_PDAC/pdacbio-channels.tsv #../../melanoma_channels.tsv #../../metabric_feature_data.tsv #../../meta_data.txt

#non_proteins: ../../metabric_non_proteins.txt #don't always need this




