## config file for hyperparameter sweep in wandb

program: run_hmivae.py
method: grid
name: basel_sweep
metric:
    goal: maximize
    name: recon_lik_test
parameters:
    batch_size:
        values: [3937,5249,7874,15749,39373]
    random_seed:
        values: [0,1,42,123,1234]
    hidden_layer_size:
        values: [8,32,64]
    latent_space_size:
        values: [10,20,30]
    n_hidden_layers:
        values: [1,2]